controller_list:
  - name: fake_niryo_arm_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_niryo_hand_controller
    joints:
      []